package com.github.dspirov.elevator.model;

/**
 * Requests generated by the user. Typically pressing the button on the elevator on each floor.
 *
 * Created by dspirov on 29/07/16.
 */
class UserRequest {

    private final int to;
    private final Direction direction;

    public UserRequest(int to, Direction direction) {
        this.to = to;
        this.direction = direction;
    }

    public Integer getTo() {
        return to;
    }

    public Direction getDirection() {
        return direction;
    }
}
